name: TagTool Build

on:
  push:
    branches: [ "mcc" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Determine Version
      id: determine_version
      run: |
        $version = (git rev-parse --short=8 HEAD).Trim()
        Write-Output "Version determined: $version"
        Write-Host "::set-output name=version::$version"

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Install 7Zip
      run: |
        Invoke-WebRequest -Uri "https://www.7-zip.org/a/7z1900-x64.msi" -OutFile "$env:TEMP\7z.msi"
        Start-Process -Wait -FilePath msiexec -ArgumentList "/i", "$env:TEMP\7z.msi", "/quiet" 

    - name: Restore Packages
      run: nuget restore TagTool.sln


    - name: Build solution
      run: msbuild TagTool.sln -t:rebuild -property:Platform=x64 -property:Configuration=Release

    - name: Zip Release
      run: |
        & "C:\Program Files\7-Zip\7z.exe" a release_mcc_x64.7z ./TagTool/bin/x64/Release/*


    - name: Fetch Last Tag
      id: fetch_last_tag
      run: |
        last_tag=$(git describe --abbrev=0 --tags 2>/dev/null || echo '2.0.0')
        echo "::set-output name=tag::$last_tag"
      
    - name: Get Current Version
      id: get_current_version
      run: echo "::set-output name=current_version::${{ steps.fetch_last_tag.outputs.tag }}"
      
    - name: Increment Version
      id: increment_version
      run: |
        $currentVersion = '${{ steps.get_current_version.outputs.current_version }}'
        $versionParts = $currentVersion -split '\.'
        $major = [int]$versionParts[0]
        $minor = [int]$versionParts[1]
        $patch = [int]$versionParts[2] + 1
        $newVersion = "$major.$minor.$patch"
        Write-Output $newVersion
        echo "::set-output name=new_version::$newVersion"

        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release_mcc_x64.7z
        tag_name: "mcc_${{steps.increment_version.outputs.new_version}}"
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
